# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: Matt Stockton

author:
  name: Matt Stockton
  email: mattstockton@gmail.com
  bio: "AI strategy consultant and software engineer sharing practical insights from real implementations."
  avatar: "/assets/images/avatar.jpg"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mstockton"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mattstockton/"

description: >- # this means to ignore newlines until "baseurl:"
  Practical AI implementation and software engineering insights from real projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mattstockton.com" # the base hostname & protocol for your site

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.26.0"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag

# Better related posts
lsi: false

# Exclude from processing.
exclude:
  - CLAUDE.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


minimal_mistakes_skin: "dirt"

# Permalink structure for posts - explicitly exclude categories
permalink: /:year/:month/:day/:title.html

# Force Jekyll to ignore categories in permalinks

defaults:
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
      layout: single
      permalink: /:year/:month/:day/:title.html
      author_profile: true
      share: true
      related: true

# Social sharing configuration
social_share:
  twitter: true
  facebook: true
  linkedin: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mstockton"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mattstockton/"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-HFEW5N1H7X"
    anonymize_ip: false # default

# SEO settings
twitter:
  username: "mstockton"

social:
  type: Person
  name: Matt Stockton
  links:
    - "https://twitter.com/mstockton"
    - "https://www.linkedin.com/in/mattstockton/"

head_scripts:
  - https://cdn-cookieyes.com/client_data/cc3cc7c737387cca67e28af5/script.js
